### ISSUE TITLE
Verifying requests

### ISSUE THREAD

**Issue by MSamman** [mrjones/oauth#37]
I've looked through the API a bit and it seems like it is designed around providing the capability to send a signed request but not necessarily verify an incoming OAuth request.

I was wondering if there is anyway to verify a incoming OAuth request using this library?

**Comment by mrjones** [comment]
Unfortunately, you're right.  Of the three parties involved in an OAuth transaction: the service provider (e.g. twitter), the end-user, and the third-party application (aka the "Consumer"), this library is designed to implement the third part app / consumers.

After a brief look, I didn't see an obvious service provider for OAuth 1.0 in golang.   However, it looks like if you're willing to use OAuth 2.0, there is a service provider implementation here: https://github.com/RangelReale/osin

I'm going to close this for now, but feel free to re-open if you have more questions!
